spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/phuket?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  rabbitmq:
    username: guest
    password: guest
    port: 5673
    host: 127.0.0.1

  #163邮箱设置
  mail:
    host: smtp.163.com #邮箱服务器地址
    username: huangding520156@163.com
    password: Hd520156
    default-encoding: UTF-8



server:
  port: 8810



swagger:
  host: 127.0.0.1:${server.port}

#sql 打印
logging:
  level:
    org.huangding.redismqregister.dao: debug
    root: INFO
    org.springframework.web: DEBUG









